## 동기 
청소기 -> 빨래-> 쓰레기통 -> 분리수거 
동시에 아님

호준: 청소기, 쓰레기통 비우기
재현: 빨래, 분리수거

## 비동기
청소기 -> 쓰레기통
빨래 -> 분리수거
동시에 일을 진행

콜백함수 탈출 방법
1. 기명합수로 변경
2. 프로미스

## 프로미스(비동기)
- promise에는 3가지 단계가 있다.
    - pending: 대기상태
    - fulfilled: 이행상태
    - rejected: 실패상태


let p = new Promise(function(resolve, reject) {
    resolve('hello world');
}).then(메시지 => {
    alert(메시지);
    return 메시지.split(' ')[0]
}).then(메시지 => {
    alert(메시지);
    return 메시지[0]
}).then(메시지 => {
    alert(메시지);
});

- 리턴된 값이 다음 함수의 아규먼트로 들어간다.
- 성공했을 땐 then, 실패하면 catch로 바로 실행된다.
- 성공이어도 throw error를 만나면 중간을 뛰어넘고 catch로 실행
- finally는 성공/실패 상관없이 실행

## async 함수
항상 반환값을 resolved로 하는 프로미스로 반환
프로미스가 펜딩이 풀린 후 + 다른 수행 함수가 없을 때까지 기다린 후 실행

(실무예제)
const f = fetch('https://raw.githubusercontent.com/paullabkorea/coronaVaccinationStatus/main/data/data.json')
    // response는 프로미스의 resolve에서 온 것
    .then(function(response) {
        return response.json();

    })
    .then(function(json) {
        console.log(json);
        return json
    })

## await 
백그라운드 > 테스크 큐 > 호출 스택 > 콘솔
- settimeout 변별처리 가능 백그라운드에 따로 1초 기다리고 있으니까
- 백그라운드 > 태스크큐로 가려면 호출 스택에 아무것도 남지 않아야 함 

- all을 쓰면 병렬처리
- await은 프로미스 앞에서만 사용가능하고 async와 사용하여 비동기처리를 한다.
- 병렬처리를 하지 않는 것은 각자 await를 선언했기 때문에 비동기 처리의 효과를 보지 못하고 동기처리처럼 시간이 총 6.5초!
**- 그런데 all로 병렬처리하여 사용하면 비동기적으로 처리할 수 있어 총 5초만 걸려서 세 개의 값이 동시에 나온 것.**

function cook(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
}

const myCake = async () => {
        await cook(1000);
        return '케이크';
};

const myCoffee = async () => {
      await cook(500);
      return '커피';
};
const myCookie = async () => {
      await cook(5000);
      return '쿠키';
};

async function asyncProcess() {
      const cake = await myCake();
      console.log(cake);
      const coffee = await myCoffee();
      console.log(coffee);
      const cookie = await myCookie();
      console.log(cookie);
}

asyncProcess();
console.log('hello world');

// 시간과 상관 없이 순서대로 백그라운드에 쌓이기 때문에 순서가
hello > 케이크 > 커피 > 쿠키


## 자습시간 질문
- 콜백 지옥 개념 
- await..? 
- 



// 민석님
async function a() {
    console.log(1);
    await new Promise( resolve => setTimeout(()=> {
         console.log(2);
        resolve();
    },3000));
    console.log(3)
}

a()

//기훈님
async function a() {
    console.log(1);
    await setTimeout(()=> {
         console.log(2)   
    },3000);
    console.log(3)
}

a()



await 키워드는 반드시 프로미스 앞에서 사용해야한다고 나와있더라구요
setTimeout이 프로미스가 아니라서 저런 현상이 발생한것 같습니당